### ISSUE TITLE
No HMR on Symfony/Vuejs, use LiveReaload

### ISSUE THREAD

**Issue by andrelec1** [rompetomp/inertia-bundle#19]
I don't know if this is the best place to tell this ... 
but
With the Symfony => Inertia => vuejs we loose the HMR 
( you can't use the webpack-encore server because you need the symfony render ... )

Today using a HMR is obvious for dev, but with this stack you can't ...
So after some researche we can use a old cousin of HMR: LiveReload

3 Step to get ready : 

- `npm install --save-dev webpack-livereload-plugin`

- in webpack.config.js add : 
```js
        if (!Encore.isProduction()) {
            Encore.addPlugin(new LiveReloadPlugin());
        }
```

- in your main twig template add :
```twig
        {% if app.debug %}
            <script src="http://localhost:35729/livereload.js"></script>
        {% endif %}
```

**Comment by rompetomp** [comment]
Hmm, for me, the encore dev-server just works, I don't need anything special

**Comment by andrelec1** [comment]
So i miss something ...

How vuejs can be serve by webpack encore if the data ( and template html ) is render in twig serve by my apache ? 
Webpack encore have php in it and i miss config something ?

**Comment by rompetomp** [comment]
Maybe this is what you're looking for? https://symfony.com/doc/current/frontend/encore/dev-server.html

**Comment by andrelec1** [comment]
Ok , i have the same config as you ...
but on my localhost:8080 i have a 'cannot get /' ...

So this my thinking ( tell me if i'm wrong ) :

webpack-encore transpile vuejs source into a js file ...
webpack-encore serveur my '/public/' folder ....
I have a index.php and .htaccess in my '/public/'...
How Webpack can interprete my index.php ?

**Comment by rompetomp** [comment]
I think you're making it harder than it should. You don't need to go to localhost:8080. Just make sure the `encore_entry_script_tags('app')` is in your twig file, and then it should automatically include the javascript files. Just go to the endpoint defined in your Symfony setup

**Comment by rompetomp** [comment]
Like I said, you don't need to go to localhost:8080, that's the dev server, you need to go to your symfony project's endpoint, whichever that is

**Comment by andrelec1** [comment]
Hoo god ... i just understand why noting work ... 

I have a silence CORS error -_-" ....

`encore dev-server --disable-host-check --hot --watch` and magic append :)
