### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by aleksblendwerk** [rompetomp/inertia-bundle#24]
I would like to add compatibility for `8.0` in `composer.json`.

That means there also have to be tests on 8.0 though... 

Currently PHPUnit 6.5 is used in the CI script which doesn't support 8.0, I propose that can be bumped up to the latest greatest 9.x - might need some minor changes in the tests but that should be trivial.

Also I couldn't find any info on whether Travis CI supports 8.0. Are you okay with replacing the current usage of Travis CI with an equivalent GitHub action?

If that sounds like a good approach to you, I can prepare a PR. Also I haven't really tried it on 8.0 yet but I doubt the actual code needs any changes. Will see...

**Comment by rompetomp** [comment]
I'm okay with replacing Travis with Github actions. As long as it does everything the current setup does now (+ php 8 support :-))

**Comment by rompetomp** [comment]
I will close this issue though, I'll be awaiting the PR 😉
