### ISSUE TITLE
Encore configuration examples for the available adapters

### ISSUE THREAD

**Issue by aleksblendwerk** [rompetomp/inertia-bundle#3]
First of all, thanks for providing a way to use Inertia.js with Symfony, I really want to take it for a test drive.

And this might be out of scope for your project but I still wanted to give it a shot. This project's README says:

> Find a frontend adapter that you wish to use here https://github.com/inertiajs. The README's are using Laravel's Webpack Mix. It's not hard translating this to Webpack Encore, just follow the documentation

Actually it's hard for me, as I haven't worked with Encore or Mix before and only have basic Webpack knowledge. So maybe you could provide example configurations for one or more of the available adapters.

**Comment by rompetomp** [comment]
Thanks for the feedback. 

I added some examples to the README. Please let me know if you have any more questions
