### ISSUE TITLE
Argument #1 ($url) must be of type string, null given

### ISSUE THREAD

**Issue by YummYume** [rompetomp/inertia-bundle#45]
`Rompetomp\InertiaBundle\Service\Inertia::setSsrUrl(): Argument #1 ($url) must be of type string, null given, called in /app/var/cache/dev/ContainerLcyDPuy/App  
  _KernelDevDebugContainer.php on line 1664`

Happens when executing `cache:clear` (so right after installation). It is fixed by adding an empty string as url in the `rompetomp_inertia.yaml` config file.

**Comment by rompetomp** [comment]
I’m on my phone now, but it _should_ be fixed with the latest version. Can you confirm?

**Comment by YummYume** [comment]
@rompetomp Just tested and works all fine. Thanks for the quick fix! :+1:
